-define(PARAM_REALM            , <<"realm">>).
-define(PARAM_CONSUMER_KEY     , <<"oauth_consumer_key">>).
-define(PARAM_SIGNATURE        , <<"oauth_signature">>).
-define(PARAM_SIGNATURE_METHOD , <<"oauth_signature_method">>).
-define(PARAM_TIMESTAMP        , <<"oauth_timestamp">>).
-define(PARAM_NONCE            , <<"oauth_nonce">>).
-define(PARAM_CALLBACK         , <<"oauth_callback">>).
-define(PARAM_VERSION          , <<"oauth_version">>).
